ConfigVersionId is apparently optional
From this error:
get_config: error was caused by json {'IsError': False, 'IsInProgress': True, 'Message': 'configurator.apiresponse.get.willNowContactRobot', 'ConfigId': 0, 'ConfigDateTime': '0001-01-01T00:00:00', 'ConfigValidated': False}
2026-07-10 15:36:17.381 ERROR (MainThread) [echoroboticsapi] 1 validation error for GetConfig
ConfigVersionId
  Field required [type=missing, input_value={'IsError': False, 'IsInP...ConfigValidated': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
Traceback (most recent call last):
  File "/opt/myhass-home/my-hass/venv/lib/python3.14/site-packages/echoroboticsapi/api.py", line 77, in get_config
    resp = GetConfig.model_validate(json)
  File "/opt/myhass-home/my-hass/venv/lib/python3.14/site-packages/pydantic/main.py", line 716, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj,
        ^^^^
    ...<5 lines>...
        by_name=by_name,
        ^^^^^^^^^^^^^^^^
    )
    ^
pydantic_core._pydantic_core.ValidationError: 1 validation error for GetConfig
ConfigVersionId
  Field required [type=missing, input_value={'IsError': False, 'IsInP...ConfigValidated': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing